# Generated by Django 5.0.7 on 2024-08-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='to_do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_heading', models.CharField(max_length=50)),
                ('todo_description', models.TextField()),
            ],
        ),
    ]
